// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeFooBar(a Foo, b Bar) FooBar {
	fooBar := NewFooBar(a, b)
	return fooBar
}
