// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"context"
	"github.com/DrmagicE/wire-examples/example/db"
	"github.com/DrmagicE/wire-examples/example/service"
	"io"
)

// Injectors from wire.go:

func NewService(c *db.Config, m *service.MailConfig) (*service.Service, error) {
	mailSender := service.NewMailSender(m)
	sqlDB, err := db.NewDB(c)
	if err != nil {
		return nil, err
	}
	userRepo := service.NewUserRepo(sqlDB)
	serviceService := service.NewService(mailSender, userRepo)
	return serviceService, nil
}

func InitGreeter(ctx context.Context, s []string, w io.Writer) (*service.Greeter, error) {
	options := &service.Options{
		Messages: s,
		Writer:   w,
	}
	greeter, err := service.NewGreeter(ctx, options)
	if err != nil {
		return nil, err
	}
	return greeter, nil
}
