// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/DrmagicE/wire-examples/db"
	"github.com/DrmagicE/wire-examples/service"
)

// Injectors from wire.go:

func NewService(c *db.Config, m *service.MailConfig) (*service.Service, error) {
	mailSender := service.NewMailSender(m)
	sqlDB, err := db.NewDB(c)
	if err != nil {
		return nil, err
	}
	userRepo := service.NewUserRepo(sqlDB)
	serviceService := service.NewService(mailSender, userRepo)
	return serviceService, nil
}
